apiVersion: batch/v1beta1
kind: CronJob
metadata:
  labels:
    app.kubernetes.io/instance: vaultwarden
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: vaultwarden
    app.kubernetes.io/version: 1.23.0
    helm.sh/chart: vaultwarden-0.5.1
  name: vaultwarden-backups
  namespace: vaultwarden
spec:
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      activeDeadlineSeconds: 2700
      template:
        spec:
          containers:
            - args:
                - |
                  echo "Snapshotting Database"
                  pg_dumpall --clean \
                    | gzip --rsyncable \
                    | restic backup \
                      --host 'vaultwarden' \
                      --stdin \
                      --stdin-filename 'vaultwarden.sql.gz'

                  sql_snapshot_status=$?


                  echo "Snapshotting Data Volume"
                  restic backup /data \
                    --host 'vaultwarden' \
                    --exclude='/data/icon_cache/**'

                  volume_snapshot_status=$?


                  echo "Pruning snapshots"
                  restic forget \
                    --host 'vaultwarden' \
                    --keep-last 3 \
                    --keep-daily 7 \
                    --keep-weekly 52

                  prune_status=$?



                    backup_status=0

                    if [ $sql_snapshot_status -ne 0 ]; then
                      backup_status=1
                    elif [ $volume_snapshot_status -ne 0 ]; then
                      backup_status=2
                    elif [ $prune_status -ne 0 ]; then
                      backup_status=3
                    fi

                    wget -q -O - --post-data "s=${backup_status}" https://nosnch.in/126d237239
              command:
                - /bin/sh
                - '-c'
              env:
                - name: PGHOST
                  value: vaultwarden-postgresql
                - name: PGPORT
                  value: '5432'
                - name: PGDATABASE
                  value: vaultwarden
                - name: PGUSER
                  valueFrom:
                    secretKeyRef:
                      key: POSTGRES_USER
                      name: postgresql
                - name: PGPASSWORD
                  valueFrom:
                    secretKeyRef:
                      key: POSTGRES_PASSWORD
                      name: postgresql
              envFrom:
                - secretRef:
                    name: restic
              image: 'ghcr.io/jarvusinnovations/restic-toolkit:1.2.0'
              imagePullPolicy: IfNotPresent
              name: restic-toolkit
          restartPolicy: Never
  schedule: 40 * * * *
